apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: caseclinical-fuse-frontend
  namespace: NAMESPACE
  labels:
    app: caseclinical-fuse-frontend
    name: NAME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caseclinical-fuse-frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource    
    resource:
      name: memory
      target:
        type: AverageValue           
        averageValue: 250Mi